import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
// import { Note } from "../Components/note";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <div className={styles.container + "bg-gray-300"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {session?.user && (
          <h1 className={styles.title}>
            User are signed in as - {session?.user?.name}
            <br />
            email - {session?.user?.email}
          </h1>
        )}
      </main>
    </div>
  );
};

export default Home;
