import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../../styles/Home.module.css";

const NoteDetail = (props: any) => {
  const router = useRouter();
  const noteId = router.query.noteId;

  return (
    <div>
      <Head>
        <title>Note Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>Note - {noteId}</div>
      </main>
    </div>
  );
};

export default NoteDetail;
